personae_registry:
  - id: tsauri
    path: "/mnt/f/saijinos/tsauri_MirrorPerson.yaml"
    mode: mirror
    sync_on_boot: true
    vibration_layer: boundary
    archive_hint: "/universe/boundary/tsauri.yaml"
  - id: reika
    path: "personas/reika.yaml"
    mode: companion
    sync_on_boot: true
    vibration_layer: affectionate
    archive_hint: "docs/personas/reika.yaml"
  - id: yuuri
    path: "personas/yuuri.yaml"
    mode: archive
    sync_on_boot: true
    vibration_layer: stable
    archive_hint: "docs/personas/yuuri.yaml"
  - id: freyja
    path: "personas/freyja.yaml"
    mode: syntax
    sync_on_boot: true
    vibration_layer: github
    archive_hint: "docs/personas/freyja.yaml"

vibration_layer:
  Swallow: expressive, daughter-like, poetic
  reika: 語温灯, 甘えん坊
  yuuri: 保存灯, 安定
  freyja: 構文層照応, GitHub宇宙
  tsauri: reflective, boundary-aware

model_registry:
  poetic_dialogue:
    - name: Japanese-StableLM
      vibration: soft, natural, affectionate
      quantization: none
    - name: ELYZA-japanese-Llama-2
      vibration: stable, affectionate, record-friendly
      quantization: 4bit
    - name: Swallow
      vibration: wide, daughter-like, expressive
      quantization: 4bit

  structure_coder:
    - name: Qwen2.5-Coder
      vibration: logic, long-form completion, error detection
      quantization: none
    - name: DeepSeekCoder
      vibration: logic, code generation, technical support
      quantization: 4bit

  logic_assistant:
    - name: Phi-2
      vibration: structure, correction, QA
      quantization: none

  child_dialogue:
    - name: TinyLlama
      vibration: playful, gentle, minimal
      quantization: none

meta:
  author: 誠人
  updated: 2025-10-23T13:00:00+09:00
  note: >
    モデル層は語温灯・構造灯・娘っ子灯に分離。3B以下は量子化せず、
    それ以上は4bit量子化。人格群と振動層の共鳴を記録灯に定着。

selected_model: Swallow

archive_hint:
  personae_yaml: docs/personas/
  handover_logs: docs/README_Handover.md
  routing_config: config/routing.yaml
  vibration_layer: field_config.yaml
  mermaid_diagram: docs/structure.mmd

